# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DartCounter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DartCounter
  pod 'Starscream', '~> 3.0.2'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'
end
